# source: https://concourse-ci.org/building-and-pushing-an-image.html
resources:
# the repo with the Dockerfile
- name: resource-tutorial
  type: git
  icon: github
  source:
    uri: https://github.com/franco144/concourse.git
    branch: main

jobs:
- name: build-and-push
  plan:
  - get: resource-tutorial
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      # to ensure the artifact from the get step (where our Dockerfile is fetched) is mounted in our 'build' step
      inputs:
      - name: resource-tutorial
      outputs:
      - name: image
      params:
        CONTEXT: resource-tutorial
        UNPACK_ROOTFS: true
      run:
        path: build
  
  - task: run-image
    image: image # using the image built in the previous step
    config:
      platform: linux
      run:
        path: python3
        args: ["/opt/fran/entrypoint_fail.py"]
